FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    wget tar cpio gzip xorriso syslinux syslinux-utils \
    dosfstools mtools qemu-utils grub-pc-bin grub-efi-amd64-bin \
    cargo rustc nasm g++ \
    qemu-system-x86 python3

# Kopiere den gesamten Code ins Image (Vermeidet Volume Mount Crash auf Windows)
WORKDIR /build
COPY . /build/

# Mache Skripte ausführbar
RUN chmod +x /build/jules-os/scripts/build.sh
